### ISSUE TITLE
exported `utils` is inaccessible

### ISSUE THREAD

**Issue by stephenmathieson** [JSBros/hedron#11]
ffe0fdbf976e49100d271bb860a04283bbb2b848 broke the namespace:

<img width="299" alt="screen shot 2016-11-11 at 10 33 48" src="https://cloud.githubusercontent.com/assets/571265/20225852/5c452c70-a7fa-11e6-9da9-c62ae5163a6f.png">

**Comment by garetmckinley** [comment]
What is the reason behind this? Still getting the hang of writing es6 modules. I thought the original syntax was wrong and corrected it to this after seeing [this](http://eslint.org/docs/rules/object-shorthand).

**Comment by stephenmathieson** [comment]
Yep, had the wrong hash! You noticed this as soon as I did!

Looks like you fixed it. Thanks!!

**Comment by garetmckinley** [comment]
Phew! I thought I broke something in my latest changes.

**Comment by stephenmathieson** [comment]
Nope, my bad! Sorry for the false alarm
