### ISSUE TITLE
Hedron breaks with babel plugin

### ISSUE THREAD

**Issue by schuylr** [JSBros/hedron#166]
Using v1.0.0-beta.12, when I add `babel-plugin-styled-components` to my `.babelrc`, everything compiles but the page reports the following:

```
hedron.js:901 Uncaught TypeError: styled.css.withConfig is not a function
    at hedron.js:901
    at Array.map (<anonymous>)
    at breakpoints (hedron.js:900)
    at new <anonymous> (hedron.js:1168)
    at flatten (styled-components.browser.esm.js:1265)
    at flatten (styled-components.browser.esm.js:1242)
    at ComponentStyle.generateAndInjectStyles (styled-components.browser.esm.js:1449)
    at StyledComponent.generateAndInjectStyles (styled-components.browser.esm.js:2036)
    at StyledComponent.renderInner (styled-components.browser.esm.js:1974)
    at renderInner (styled-components.browser.esm.js:1888)
```

My `.babelrc`:

```
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": "> 1%",
        "uglify": true
      },
      "useBuiltIns": true
    }],
    "react"
  ],

  "plugins": [
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    ["transform-class-properties", { "spec": true }],
    "babel-plugin-styled-components"
  ]
}
```

**Comment by SamMatthewsIsACommonName** [comment]
Hi @schuylr were you able to find a solution for this?

**Comment by garetmckinley** [comment]
@SamMatthewsIsACommonName is this something that is still happening?

What versions are your `styled-component` and `babel-plugin-styled-components`? I can look into this later tonight or in the morning, the more info you can give me the quicker I'll be able to resolve it :)

**Comment by SamMatthewsIsACommonName** [comment]
Hi garet, Sorry don't worry about it, it's from using an old version of Hedron (pre 1.0) and updating react scripts to 2.0, however I was just hoping there was a quick fix that meant I didn't have to migrate which i eventually found (by not having to update react scripts)... anyway long story short I'll just upgrade when we have time and I'm sure the issue doesn't exist on the latest versions. Thanks!
