### ISSUE TITLE
using justifycontent/alignitems?

### ISSUE THREAD

**Issue by dpastoor** [JSBros/hedron#24]
Hi!

Love the simplicity of this. Was previously using radium grid and decided to give this a go for a small project and its been great. Absolutely love the debug mode. 

One question, is there a way of controlling the other flexbox properties?

namely I'd like to do something like `styles={{justifyContent: 'center', alignItems: 'center'}}`

any ideas?

**Comment by garetmckinley** [comment]
Hello,

Thanks for the kind words! Currently there is not, although there definitely needs to be support for it before long 😸 

I'm going to go ahead and add this to the [v1.0.0 milestone](https://github.com/JSBros/hedron/milestone/1), so you should see it added to the library within the next month 🙌
