### ISSUE TITLE
Implement an easy way to hide/show any component based on browser width

### ISSUE THREAD

**Issue by garetmckinley** [JSBros/hedron#29]
Currently this is semi-possible if you are using `styled-components` in your project. You can simply import the (currently undocumented) `media` utility and use it like so:

``` jsx
import styled from 'styled-components';
import { utils } from 'hedron';

const OnlyVisibleOnMobile = styled.div`
  ${utils.media.sm`
    display: hidden;
  `}
`;
```

This will toggle the `display: hidden` rule only when the screen size is `sm` or larger (resulting in it only being displayed on mobile).

The problem is, this requires elements to be encapsulated. Since to hide a button, we'd essentially have to do:

``` jsx
<OnlyVisibleOnMobile>
  <Button>My Button</Button>
</OnlyVisibleOnMobile>
```

Unless of course we wanted to add the above `styled` rules onto our `Button` component. But that wouldn't be practical markup at all, as it would force all of our `Button` components to be only visible on mobile.

The next possible solution is obviously adding another prop to our `Button` component that toggles this media query on and off. But this would have to be done for every component that we want to have toggle-able media queries.

This is asking a LOT of our users, when in reality, I want this to work right out of the box.

Need to keep brainstorming...

**Comment by petehouston** [comment]
I'm thinking of setting up a prop with your above visibility wrapper components.

```
<Column>
  <Button hidden={[xs]}>Hide me on extra small screen</Button>
</Column>
```

in `Column.constructor(props)`, loop through `props.children` to see if they have any `props.hidden` then either create a wrapper component like above you stated, or add a hidden style to `children.props`.

Not sure if it works. It just pops up on my mind.

**Comment by garetmckinley** [comment]
That could work, but the problem is this will need to work for nested components and `props.children` only contains the immediate children in it. Do you know of an easy way to recursively iterate through `props.children`?

At this point I'm wondering if there's going to be a performance impact as well by doing it this way. Would definitely be a lot easier just adding a global style for `.hidden-xx`, but it breaks the concept of this grid system.

**Comment by garetmckinley** [comment]
Maybe I'll just create a public component called `Hidden` and allow it to be used like..

```jsx
<Hidden xs><Button>Click Me</Button></Hidden>
```

I think I could also have an implementation that requires zero wrapper components. I think I could simply put a loop inside the `constructor` of the `Hidden` component that iterates through it's own children, applying a `hidden` style to them. It would also be the quickest computation wise, as it's `O(N)`.
