### ISSUE TITLE
grids do not work on mobile? please help it is driving me crazy

### ISSUE THREAD

**Issue by Harryandrew** [JSBros/hedron#35]
I would like to use Hedron in my project - the grid system works just as expected on desktop however mobile seems to completely ignore the grid system. Am I doing something wrong? Please see the attached image (not very helpful sorry) - also tested from my iPhone, the grid is not registering and rendering as `lg` desktop.

https://s22.postimg.org/pdgtfmi2p/Screen_Shot_2016_11_20_at_14_22_43.png

Thanks in advance.

I will try to write you some unit tests if I get time soon

**Comment by Harryandrew** [comment]
Great! I'm a dummy: I forgot to include the meta tag:

`<meta name="viewport" content="width=device-width, initial-scale=1">`

Sorry about that

**Comment by garetmckinley** [comment]
Glad you were able to get it resolved! I should probably add that in the docs somewhere.
