### ISSUE TITLE
Question: How would one right align a column?

### ISSUE THREAD

**Issue by dnecklesportfolio** [JSBros/hedron#48]
http://www.webpackbin.com/41ytb40Nf

If I wanted to right align everything in the first column, not just the h2, how would i achieve that?

**Comment by dnecklesportfolio** [comment]
I would have to nest col/row with another one unfort

**Comment by garetmckinley** [comment]
You mean [like this](http://www.webpackbin.com/EyqHqERNf)? Not sure if I'm understanding correctly

**Comment by dnecklesportfolio** [comment]
You understand me quite right. I may have missed but can you show me in the
docs where u could add that style object... I am new to this new inline CSS
concept but I could have sworn I didn't see that you can add a style object
to the column.

**Comment by garetmckinley** [comment]
This isnt something documented in Hedron because its a feature of React. See the docs here for more info https://facebook.github.io/react/docs/dom-elements.html#style

**Comment by dnecklesportfolio** [comment]
Dang it  yes because Row and columns are component too sorry about that.
Thank you.

**Comment by garetmckinley** [comment]
No worries man, happy to help :)
