### ISSUE TITLE
Replace Row/Column with Container/Box

### ISSUE THREAD

**Issue by garetmckinley** [JSBros/hedron#56]
This is something that @matthamil and I have been discussing in our [slack](https://jsbro.slack.com) room. Basically, the `Row`/`Column` approach really doesn't make sense with flexbox, since flexboxes can be either horizontal or vertical.

Since `1.0.0` will be the first official release with breaking changes, it makes sense to go ahead and resolve the problem then rather than perpetuating an outdated `Row`/`Column` grid system.  The current `Row`/`Column` API will remain the same for all `0.x.x` releases, so no need to worry about these changes breaking your existing hedron projects. 

## The issue with the current API

If you want to make a layout that looks like this

![pasted_image_at_2017_01_19_09_43_am](https://cloud.githubusercontent.com/assets/1624279/22331829/93b11426-e39b-11e6-82a1-c7d4a74ab197.png)

It requires an uncomfortable amount of nesting.

```jsx
<Page debug>
  <Row>
    <Column xs={12} sm={6} md={4}>Header</Column>
  </Row>
  <Row>
    <Column xs={12}>Navigation</Column>
  </Row>

  <Row>
    <Column xs={12} sm={4}>
      <Row>
        <Column>Sidebar</Column>
      </Row>
      <Row>
        <Column>Some links</Column>
      </Row>
      <Row>
        <Column>Or other things</Column>
      </Row>
    </Column>
    <Column xs={12} sm={6} md={8}>
      <Row>
        <Column>First Post</Column>
        <Column>Second Post</Column>
        <Column>Third Post</Column>
      </Row>
    </Column>
  </Row>
</Page>
```

This can be resolved by implementing a way to set the `flex-direction` on the `Row` component. The biggest problem is that it introduces confusion with naming conventions. The word column refers to "a vertical division of a page or text."; so having columns that are horizontal divisions doesn't make a lot of sense.

It introduces even more confusion because the terms for `flex-direction` are either `row` or `column`.

## The proposed solution

For now, we have collectively agreed on the terms `Container` and `Box` for our grid components. These components will also abstract away the typical flex properties as well, making flexbox properties easy to configure and most importantly, easy to remember.

(These properties are open to discussion)

### Container

- `direction`: `horizontal|vertical`
  - sets the direction of the contained elements. Default: `horizontal`
- `vAlign`: `top|middle|bottom`
  - sets the vertical alignment of the contained elements. Default: `middle`
- `hAlign`: `left|center|right`
  - sets the horizontal alignment of the contained elements. Default: `center`
- `flex`: `Object`
  -  allows you to manually set any flex property. Default: `{}`
  - **Note:** flex properties are camelCased instead of kabob-case. Also, there is no need for the `flex` prefix on any of the rules. So `flex-direction` becomes `direction`.

### Box

The box will have all the same size/shift properties as `Column`. If the `direction` of the parent `Container` is set to `horizontal`, the boxes will be aligned like columns. If the `direction` is set to `vertical`, the boxes will be aligned like rows. This cuts down on the need for nesting 👍 

To create the same layout demonstrated above using the new API, it would look like this

```jsx
<Page height='500px' overflow='scroll' debug>
  <Container direction='vertical' vAlign='middle'>
    <Box xs={12} sm={6} md={4}>Header</Box>
    <Box xs={12}>Navigation</Box>
  </Container>

  <Container direction='horizontal'>
    <Box xs={12} sm={4}>
      <Container direction='vertical' vAlign='top'>
        <Box>Sidebar</Box>
        <Box>Some links</Box>
        <Box>Or other things</Box>
      </Container>
    </Box>
    <Box xs={12} sm={6} md={8}>
      <Container direction='vertical' vAlign='middle'>
        <Box>First Post</Box>
        <Box>Second Post</Box>
        <Box>Third Post</Box>
      </Container>
    </Box>
  </Container>
</Page>
```

As you can see, the code is shorter and more shallow.

This new API is still being conceptualized, and we'd love to get any feedback you have 😸 

If you want to join our discussions on slack, [click here](https://slackin-xtuseyimsc.now.sh/) to join!

**Comment by pungggi** [comment]
I absolutely agree, very clean, i like this approach> 

> **``**

**Comment by garetmckinley** [comment]
@pungggi glad you think so! This proposal is being worked on currently in the [`1.0.0`](https://github.com/JSBros/hedron/tree/1.0.0) branch. Feel free to clone it and test it out! It's still in it's early phases, so not ready to be used in a real application yet. But you can run `yarn storybook` to see it in action 😄
