### ISSUE TITLE
Fix build so that it doesn't bundle React?

### ISSUE THREAD

**Issue by jonasws** [JSBros/hedron#60]
At the moment, when using Webpack to include the module, React is bundled, causing the bundle to be much larger than necessary. Also, the `main` field in `package.json` should perhaps point to `lib/index.js`?

These may well stem from me having a bug in my webpck config, but I don't seem to have similar problems with other modules.

**Comment by garetmckinley** [comment]
Hmm, I think this is because React is listed as a dependency rather than a peer dependency. I'll investigate and see if I can patch it in the morning.

Thanks for the report!

**Comment by jonasws** [comment]
This should perhaps also be done for the `styled-components`?

**Comment by garetmckinley** [comment]
I don't think so, since having `styled-components` installed isn't a requirement. Once [`babel-plugin-styled-components`](https://github.com/styled-components/babel-plugin-styled-components) is more mature, it'll help slim down the bundle size of including `styled-components`.
