### ISSUE TITLE
Page component docs missing

### ISSUE THREAD

**Issue by Gyvastis** [JSBros/hedron#64]
Hey there. I have struggled a bit to get `hedron` working the way I wanted it to and I found the thing I was missing in the source of `Page` component. It's not specified in the docs that the `fluid` property can be used with the Page component. It now seems obvious, but for new people, this could be frustrating.

**Comment by garetmckinley** [comment]
Thanks a lot for the report, I've added some [basic documentation](https://github.com/JSBros/hedron/wiki/Grid-System#page-component) for the `Page` component.
