### ISSUE TITLE
Is 1.0.0 going to be backward compatible with 0.x.x?

### ISSUE THREAD

**Issue by chhuang** [JSBros/hedron#65]

**Comment by chhuang** [comment]
For a new project, would you recommend to use 0.x.x or wait? What is the ETA for 1.0.0?

**Comment by garetmckinley** [comment]
That depends what type of project it is. If it's a serious project that needs stability, you're probably better off using the pre `1.0.0` releases. If it's a personal project and you're willing to put up with a few bugs while it's in development, you can try out `1.0.0` by using `npm install --save hedron@next`. Just make sure to report all issues you encounter on the bug tracker and I'll try to get them resolved as soon as possible 😄 

You can see some examples of `1.0.0` usage on this storybook: https://35aca43a-4bb2-430d-afe9-a23e2a8d43cf.sbook.io

**Comment by garetmckinley** [comment]
1.0.0 is nearing release and will not be backwards compatible. We're still working on the documentation, but you can demo it on http://hedron.rocks
