### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by olegreznichenko** [JSBros/hedron#69]
What do you say to split the modules into files?
```javascript
import Row from 'hedron/Row'
```

**Comment by garetmckinley** [comment]
What would be the biggest advantage of doing this? I know for large libraries this would help cut down on size, but in order to use hedron you really have to use all the available components.

I might be missing something though, I'm not incredible knowledgable on optimizing size!

**Comment by olegreznichenko** [comment]
Hedron size in my bundle is 95kb, event if i replace like this 
P.S. webpack takes in default `dist/hedron.js`
```javascript
new webpack.NormalModuleReplacementPlugin(/hedron/, require.resolve(process.cwd() + '/node_modules/hedron/dist/hedron.es.js'))
```
size the same
in `hedron.es.js` i dont se normal ` import styled-components`, and when webpack build. he dont understand hedron's styled-components, and in output i have double "styled-components".
Mine is first, which i build UI. second hedron`s

**Comment by garetmckinley** [comment]
The hedron bundle is now down to `14kb`, the `1.0.0` branch is down to `8kb` 🙌
