### ISSUE TITLE
SSR Components render unstyled at first when used with SSR

### ISSUE THREAD

**Issue by gregorskii** [JSBros/hedron#71]
I am finding when I include Hedron in a SSR app the initial display of the component from the markup is missing the styling. After loading React rerenders with the correct styles.

This is likely related to `styled-components`, but I don't know what I need to add to make this work. I am already doing a bunch of work on my server bundle and client bundle for css-modules. Does this library require me to do anything specific for the SSR to work?

Thanks

**Comment by gregorskii** [comment]
I tried the babel plugin for styled components, did not work for me.

`babel-plugin-styled-components`

**Comment by bntzio** [comment]
@gregorskii what i did to fix this some time ago on my site was to replace the hedron style components (Row, Page, Column) in my styled-components file, something like this:

```javascript
import { Page as HedronPage } from 'hedron';

export const Page = styled(HedronPage)`
  ${props =>
    props.fluid
    ? 'width: 100%;'
    : `
      margin: 0 auto;
      max-width: 100%;
      ${props.width
        ? `width: ${props.width};`
        : 'width: 960px;'
      }
    `
  }
`;
```

With that, the SSR will work on your app, since you're already server-side rendering your styled-components I guess, the thing is, Hedron doesn't add support for SSR as far as I know.

Check my full commit on the fix here https://github.com/bntzio/site/commit/b5e805f79f4ed2f2b9c36e1a23c81b328fd4ff99 and here https://github.com/bntzio/site/commit/d88e2faff13b84a8135e85fe9d38929d095e67fd

Cheers!

**Comment by gregorskii** [comment]
Thanks, seems like a workaround. Any plans to make Herron support SSR? I think it would need a webpack plugin to auto compile the styled-components.

**Comment by garetmckinley** [comment]
I'll have to do some research into how to make hedron compatible with SSR. If anyone has any ideas I'd love to hear them, since I myself don't really use SSR :+1:

**Comment by gregorskii** [comment]
I think it has to do with compiling `styled-components` code with babel internally before realizing the dist version of this code. Or if one wants to use the raw components uncompiled having a webpack loader that compiles `styled-components`. The issue now is one would have to add webpack config to handle styled components in the server script builder.

I am not an expert on SSR, working through it right now as well.

It is interesting to me that it works on the client, maybe It is because I am using postCSS on my client build, I was trying to avoid using a complex webpack config to handle styles on the server, but due to other findings I have had to add it. My thinking is if it works on the client it would have to work on the server now with my updated config, 

I have since moved the project I am working on to `reactstrap` per the developers requesting bootstrap 4. So I do not have a config that includes Hedron. I could add it back to test if it compiles now. But my inclination is that it should.

Maybe someone else has some ideas?

**Comment by dfrankland** [comment]
I was able to get SSR to work very nicely with `styled-components`, but I am afraid I may have changed too much of the build process of `hedron` along the way. If you want to test it out, install `@dfrankland/hedron` and give it a spin.

Here's my branch where I've gotten everything working: https://github.com/dfrankland/hedron/tree/fix-ssr

@garetmckinley, I don't mind opening a PR, but what do you think of these changes:
https://github.com/JSBros/hedron/compare/1.0.0...dfrankland:fix-ssr

**Comment by dfrankland** [comment]
I've simplified my changes and opened 2 pull requests for the v1.0.0 and master branches: #75, #76.

As I mentioned before I have tested using `styled-components@^2.0.0` + `babel-plugin-styled-components@^1.1.4` + [next.js](https://github.com/zeit/next.js)

**Comment by garetmckinley** [comment]
Thanks for your work ! :tada: I'll try to review the changes either tonight or tomorrow.

**Comment by garetmckinley** [comment]
@dfrankland so I merged both your PRs, and it looks like at least the `1.0.0` branch is still having issues with SSR 😕

[Here's a website deployed with next.js using `styled-components@2.0.0` and `hedron@next`.](https://hedron-site-pbphbvgjll.now.sh/)

**Comment by dfrankland** [comment]
Hmmm, that's not right. Let me see if I can make a nice quick demo too. I've got `hedron@next` working just fine with `styled-components@2.0.0` and next.js.

**Comment by dfrankland** [comment]
@garetmckinley, looking at the source page for the website you deployed: https://zeit.co/UOLFz5gDdpr7Itczn7codrDh/hedron-site/pbphbvgjll/source

I don't see your `.babelrc` with a config including `babel-plugin-styled-components`. SSR won't work without it.

**Comment by garetmckinley** [comment]
🤦‍♂️

**Comment by garetmckinley** [comment]
@dfrankland so it's still not working for me :slightly_frowning_face: 

https://hedron-site-hevnmaqkau.now.sh/

my `.babelrc` looks like

```
{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    [
      "styled-components",
      {
        "ssr": true,
        "preprocess": true,
        "minify": true
      }
    ]
  ]
}
```

I'm not very experienced using next.js, so I'm sure it's probably my mistake

**Comment by dfrankland** [comment]
@garetmckinley, no worries 👌 .

Here's an example with it working: https://hedron-nextjs-ssr-example-vgnzwutwxi.now.sh/

If you'd like to see the source checkout this repo: https://github.com/dfrankland/hedron-nextjs-ssr-example

That example is based on this one: https://github.com/zeit/next.js/tree/master/examples/with-styled-components

**Comment by garetmckinley** [comment]
Do you think it could be the absence of the `_document.js` file in my project? That's the only visible difference I can see. I was unsure what the actual point of the document was when I was looking over the official docs. I figured next.js shipped with some sort of sensible defaults for rendering the document. But again, I don't know a ton about next. I'll give it a try and see if it fixes my issues.

Thanks again for getting SSR to work properly with hedron :trophy: it was something a lot of people asked me about, and I was unsure how to get it working myself.

**Comment by garetmckinley** [comment]
Ah, that did the trick! I'm curious why it wouldn't work without that.

**Comment by dfrankland** [comment]
Not a problem, glad that I could help out! 👍 

`_document.js` is used to collect the styles from the rendered page, then insert them as a string into the `<html>...</html>` response. The built-in `_document.js` isn't aware of collecting styles in a way that `styled-components` would need, therefore a custom `_document.js` is needed.

**Comment by garetmckinley** [comment]
Makes sense, thanks for the explanation! I suppose I can close out this issue now :smile:
