### ISSUE TITLE
getting prop-types warning...

### ISSUE THREAD

**Issue by therealedsheenan** [JSBros/hedron#72]
![screen shot 2017-05-09 at 10 46 59](https://cloud.githubusercontent.com/assets/10054876/25832337/ea62bfa4-34a4-11e7-8027-f88233d05e2b.png)

Any idea about this?

**Comment by garetmckinley** [comment]
Did you upgrade to the latest release? `0.6.1` should have this resolved

**Comment by therealedsheenan** [comment]
Sorry my bad. I have updated the dependency.
