### ISSUE TITLE
yarn.lock

### ISSUE THREAD

**Issue by stephenmathieson** [JSBros/hedron#8]
Should remove the `yarn.lock` file here. See https://medium.com/@boennemann/avoid-yarn-for-packages-and-fully-enjoy-its-benefits-for-application-development-8bdd4deb33cf#.m0v06nkbu for more info

**Comment by garetmckinley** [comment]
Yeah that would be great. Originally I was under the impression it was as good thing to commit. Thanks for the reading material :+1:
