### ISSUE TITLE
Support Server Side Rendering

### ISSUE THREAD

**Issue by sonnenfeld269** [JSBros/hedron#81]
I am using next.js for server side rendering. I managed to use styled components because they support ssr now, but I have still problems with hedron.

**Comment by garetmckinley** [comment]
Hedron supports SSR as well in both `0.7.1` and `1.0.0-beta.6`. You need to elaborate on what you're having problems with.

**Comment by garetmckinley** [comment]
SSR was discussed a bunch in #71, make sure you have the babel plugin working.

**Comment by sonnenfeld269** [comment]
yes, updated to a new version, now its working...
